apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: git@github.com:eoyewobi/api_config.git
    targetRevision: HEAD
    path: api
  destination:
    server: https://kubernetes.default.svc
    namespace: api

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true